TriggerEvent('es:addGroupCommand', 'n0', "mod", function(source, args, user)
	TriggerClientEvent("salgado:noclip0", source)
end, function(source, args, user)
	TriggerClientEvent('chat:addMessage', source, { args = {"Servidor", " Permissões Insuficientes!"} })
end, {help = "Noclip Velocidade Nível 0 by João Pedro Salgado"})

TriggerEvent('es:addGroupCommand', 'n1', "mod", function(source, args, user)
	TriggerClientEvent("salgado:noclip1", source)
end, function(source, args, user)
	TriggerClientEvent('chat:addMessage', source, { args = {"Servidor", " Permissões Insuficientes!"} })
end, {help = "Noclip Velocidade Nível 1 by João Pedro Salgado"})

TriggerEvent('es:addGroupCommand', 'n2', "mod", function(source, args, user)
	TriggerClientEvent("salgado:noclip2", source)
end, function(source, args, user)
	TriggerClientEvent('chat:addMessage', source, { args = {"Servidor", " Permissões Insuficientes!"} })
end, {help = "Noclip Velocidade Nível 2 by João Pedro Salgado"})

TriggerEvent('es:addGroupCommand', 'n3', "mod", function(source, args, user)
	TriggerClientEvent("salgado:noclip3", source)
end, function(source, args, user)
	TriggerClientEvent('chat:addMessage', source, { args = {"Servidor", " Permissões Insuficientes!"} })
end, {help = "Noclip Velocidade Nível 3 by João Pedro Salgado"})

TriggerEvent('es:addGroupCommand', 'n4', "mod", function(source, args, user)
	TriggerClientEvent("salgado:noclip4", source)
end, function(source, args, user)
	TriggerClientEvent('chat:addMessage', source, { args = {"Servidor", " Permissões Insuficientes!"} })
end, {help = "Noclip Velocidade Nível 4 by João Pedro Salgado"})

TriggerEvent('es:addGroupCommand', 'n5', "mod", function(source, args, user)
	TriggerClientEvent("salgado:noclip5", source)
end, function(source, args, user)
	TriggerClientEvent('chat:addMessage', source, { args = {"Servidor", " Permissões Insuficientes!"} })
end, {help = "Noclip Velocidade Nível 5 by João Pedro Salgado"})